# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/RVfpgaLab/RVfpgaSoc_1/Lab8ADXL/Lab8ADXL.srcs/sources_1/bd/swerv_soc/ip/swerv_soc_axi_iic_0_0/swerv_soc_axi_iic_0_0.xci
# IP: The module: 'swerv_soc_axi_iic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/RVfpgaLab/RVfpgaSoc_1/Lab8ADXL/Lab8ADXL.srcs/sources_1/bd/swerv_soc/ip/swerv_soc_axi_iic_0_0/swerv_soc_axi_iic_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'swerv_soc_axi_iic_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/RVfpgaLab/RVfpgaSoc_1/Lab8ADXL/Lab8ADXL.srcs/sources_1/bd/swerv_soc/ip/swerv_soc_axi_iic_0_0/swerv_soc_axi_iic_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'swerv_soc_axi_iic_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/RVfpgaLab/RVfpgaSoc_1/Lab8ADXL/Lab8ADXL.srcs/sources_1/bd/swerv_soc/ip/swerv_soc_axi_iic_0_0/swerv_soc_axi_iic_0_0.xci
# IP: The module: 'swerv_soc_axi_iic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/RVfpgaLab/RVfpgaSoc_1/Lab8ADXL/Lab8ADXL.srcs/sources_1/bd/swerv_soc/ip/swerv_soc_axi_iic_0_0/swerv_soc_axi_iic_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'swerv_soc_axi_iic_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/RVfpgaLab/RVfpgaSoc_1/Lab8ADXL/Lab8ADXL.srcs/sources_1/bd/swerv_soc/ip/swerv_soc_axi_iic_0_0/swerv_soc_axi_iic_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'swerv_soc_axi_iic_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
